apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: app
        image: marcozavaletab/application:v1
        env:
        - name: DATABASE_HOST
          value: my-service-mysql
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: database
