apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-mysql
  template:
    metadata:
      labels:
        app: pod-mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        envFrom:
        - configMapRef:
           name: custom-config-mysql
